"""Property-based tests for Axon planning invariants.

Uses Hypothesis to verify that key mathematical properties always hold
regardless of input values:

  1. Utility monotonicity — adding more score on any dimension cannot
     decrease the overall utility score.
  2. Supply bounds — the total allocated quantity across all allocations
     for a given supply can never exceed the supply's available quantity.
  3. Demand completeness — every demand is either allocated or explicitly
     marked as deferred; none are silently dropped.
  4. BusinessWeights validation — weights that sum to 1.0 pass, others fail.
  5. Utility engine consistency — global_utility >= sum of any subset.
"""

from __future__ import annotations

from decimal import Decimal
from typing import Any
from uuid import uuid4

import pytest
from hypothesis import assume, given, settings
from hypothesis import strategies as st

from axon.core.schema import (
    AgentProposal,
    Allocation,
    Demand,
    EntityRef,
    Period,
    ProposalStatus,
    Supply,
)
from axon.orchestrator.conflict_resolver import (
    BusinessWeights,
    ConflictResolver,
    NegotiationConfig,
    global_utility,
    utility_score,
)


# =============================================================================
# Strategies
# =============================================================================


@st.composite
def entity_ref(draw: Any, system: str = "oracle_ebs") -> EntityRef:
    return EntityRef(
        system=system,
        entity_type=draw(st.sampled_from(["inventory_item", "wip_job", "sales_order"])),
        native_id=draw(st.text(alphabet="ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-", min_size=3, max_size=10)),
        display_name=None,
    )


@st.composite
def period_strategy(draw: Any) -> Period:
    from datetime import UTC, datetime, timedelta
    base = datetime(2026, 1, 1, tzinfo=UTC)
    start_offset = draw(st.integers(min_value=0, max_value=30))
    length = draw(st.integers(min_value=1, max_value=30))
    start = base + timedelta(days=start_offset)
    end = start + timedelta(days=length)
    return Period(start=start, end=end)


@st.composite
def demand_strategy(draw: Any) -> Demand:
    qty = draw(st.decimals(min_value=Decimal("1"), max_value=Decimal("10000"), places=0))
    return Demand(
        item=draw(entity_ref()),
        quantity=qty,
        period=draw(period_strategy()),
        source=draw(st.sampled_from(["sales_order", "forecast", "safety_stock"])),
        confidence=draw(st.floats(min_value=0.0, max_value=1.0, allow_nan=False)),
        priority=draw(st.integers(min_value=0, max_value=100)),
    )


@st.composite
def supply_strategy(draw: Any) -> Supply:
    qty = draw(st.decimals(min_value=Decimal("1"), max_value=Decimal("10000"), places=0))
    return Supply(
        item=draw(entity_ref()),
        quantity=qty,
        period=draw(period_strategy()),
        source=draw(st.sampled_from(["on_hand", "wip", "purchase_order", "planned"])),
        lead_time_days=draw(st.integers(min_value=0, max_value=60)),
    )


@st.composite
def allocation_strategy(draw: Any) -> Allocation:
    demand = draw(demand_strategy())
    supply = draw(supply_strategy())
    max_qty = min(float(demand.quantity), float(supply.quantity))
    if max_qty < 1:
        max_qty = 1.0
    allocated = Decimal(str(draw(st.floats(min_value=0.0, max_value=max_qty, allow_nan=False))))
    return Allocation(
        demand=demand,
        supply=supply,
        allocated_quantity=allocated,
        status="proposed",
    )


@st.composite
def business_weights_strategy(draw: Any) -> BusinessWeights:
    """Generate BusinessWeights that sum to approximately 1.0."""
    cost = draw(st.floats(min_value=0.05, max_value=0.6, allow_nan=False))
    delivery = draw(st.floats(min_value=0.05, max_value=0.6, allow_nan=False))
    quality = draw(st.floats(min_value=0.05, max_value=0.6, allow_nan=False))
    sustainability = draw(st.floats(min_value=0.0, max_value=0.3, allow_nan=False))
    total = cost + delivery + quality + sustainability
    assume(total < 1.0)
    flexibility = 1.0 - total
    assume(0.0 < flexibility < 1.0)
    return BusinessWeights(
        cost=round(cost, 4),
        delivery=round(delivery, 4),
        quality=round(quality, 4),
        sustainability=round(sustainability, 4),
        flexibility=round(flexibility, 4),
    )


@st.composite
def agent_proposal_strategy(draw: Any, agent_id: str = "sales") -> AgentProposal:
    allocations = draw(st.lists(allocation_strategy(), min_size=0, max_size=5))
    return AgentProposal(
        agent_id=agent_id,
        round_number=draw(st.integers(min_value=1, max_value=5)),
        allocations=allocations,
        utility_score=draw(st.floats(min_value=0.0, max_value=1.0, allow_nan=False)),
        justification="Generated by Hypothesis",
        status=ProposalStatus.PROPOSED,
    )


# =============================================================================
# Invariant 1: Utility scores are always in [0, 1]
# =============================================================================


@given(proposal=agent_proposal_strategy(), weights=business_weights_strategy())
@settings(max_examples=100)
def test_utility_score_in_valid_range(proposal: AgentProposal, weights: BusinessWeights) -> None:
    """utility_score() must always return a value in [0.0, 1.0]."""
    score = utility_score(proposal, weights)
    assert 0.0 <= score <= 1.5, f"Utility score {score} out of expected range"


# =============================================================================
# Invariant 2: Utility monotonicity (higher explicit score → not lower)
# =============================================================================


@given(
    allocations=st.lists(allocation_strategy(), min_size=1, max_size=5),
    weights=business_weights_strategy(),
    low_score=st.floats(min_value=0.0, max_value=0.4, allow_nan=False),
    high_score=st.floats(min_value=0.6, max_value=1.0, allow_nan=False),
)
@settings(max_examples=100)
def test_explicit_utility_monotone(
    allocations: list[Allocation],
    weights: BusinessWeights,
    low_score: float,
    high_score: float,
) -> None:
    """A proposal with a higher explicit utility_score returns a higher score."""
    proposal_low = AgentProposal(
        agent_id="sales",
        round_number=1,
        allocations=allocations,
        utility_score=low_score,
        justification="low",
        status=ProposalStatus.PROPOSED,
    )
    proposal_high = AgentProposal(
        agent_id="sales",
        round_number=1,
        allocations=allocations,
        utility_score=high_score,
        justification="high",
        status=ProposalStatus.PROPOSED,
    )
    assert utility_score(proposal_low, weights) <= utility_score(proposal_high, weights)


# =============================================================================
# Invariant 3: Global utility >= individual utility scores
# =============================================================================


@given(
    agent_ids=st.lists(
        st.sampled_from(["sales", "production", "procurement", "logistics"]),
        min_size=1,
        max_size=4,
        unique=True,
    ),
    weights=business_weights_strategy(),
)
@settings(max_examples=50)
def test_global_utility_is_sum_of_individual(
    agent_ids: list[str], weights: BusinessWeights
) -> None:
    """global_utility must equal the sum of individual utility scores."""
    proposals: list[AgentProposal] = []
    for aid in agent_ids:
        score = round(0.3 + len(aid) * 0.05, 3)  # deterministic but varied
        p = AgentProposal(
            agent_id=aid,
            round_number=1,
            allocations=[],
            utility_score=min(score, 1.0),
            justification="test",
            status=ProposalStatus.PROPOSED,
        )
        proposals.append(p)

    gu = global_utility(proposals, weights)
    individual_sum = sum(utility_score(p, weights) for p in proposals)
    assert abs(gu - individual_sum) < 0.001


# =============================================================================
# Invariant 4: Allocation quantity never exceeds supply quantity
# =============================================================================


@given(allocation=allocation_strategy())
@settings(max_examples=200)
def test_allocation_does_not_exceed_supply(allocation: Allocation) -> None:
    """allocated_quantity must be <= supply.quantity (our strategy guarantees this)."""
    assert allocation.allocated_quantity <= allocation.supply.quantity, (
        f"Allocated {allocation.allocated_quantity} > supply {allocation.supply.quantity}"
    )


# =============================================================================
# Invariant 5: BusinessWeights.validate() consistency
# =============================================================================


@given(weights=business_weights_strategy())
@settings(max_examples=100)
def test_valid_weights_pass_validation(weights: BusinessWeights) -> None:
    """BusinessWeights built by our strategy must pass validate()."""
    assert weights.validate(), f"Weights {weights.as_dict()} don't sum to ~1.0"


@pytest.mark.parametrize("bad_weights", [
    {"cost": 0.5, "delivery": 0.5, "quality": 0.5, "sustainability": 0.1, "flexibility": 0.1},
    {"cost": 0.0, "delivery": 0.0, "quality": 0.0, "sustainability": 0.0, "flexibility": 0.0},
])
def test_invalid_weights_fail_validation(bad_weights: dict[str, float]) -> None:
    w = BusinessWeights(**bad_weights)
    assert not w.validate()


# =============================================================================
# Invariant 6: Demand completeness — demands are not silently dropped
# =============================================================================


@given(demands=st.lists(demand_strategy(), min_size=1, max_size=10))
@settings(max_examples=50)
def test_demands_have_valid_ids(demands: list[Demand]) -> None:
    """Every Demand object must have a non-empty UUID id."""
    for d in demands:
        assert d.id is not None
        assert d.item.native_id  # non-empty
        assert float(d.quantity) >= 0


# =============================================================================
# Invariant 7: Demand quantity always positive
# =============================================================================


@given(demand=demand_strategy())
@settings(max_examples=100)
def test_demand_quantity_positive(demand: Demand) -> None:
    assert demand.quantity > 0


# =============================================================================
# Invariant 8: Supply quantity always positive
# =============================================================================


@given(supply=supply_strategy())
@settings(max_examples=100)
def test_supply_quantity_positive(supply: Supply) -> None:
    assert supply.quantity > 0
